---
- hosts: all
  sudo: true
  tasks:
    # prepare (MySQL-python is needed for ansible)
    - name: install epel
      yum: name=epel-release state=latest
    - name: add remi repo
      yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present
    - name: install packages
      yum: name=mysql-server,MySQL-python state=latest enablerepo=remi
    - file: path=/var/log/mysqld state=directory owner=mysql group=mysql
    - service: name=mysqld state=started
    # create db
    - mysql_db: name=testdb state=present login_user=root encoding=utf8
    # db user
    - mysql_user: name=tesdb_admin login_user=root host=localhost password='testpass' priv=testdb.*:all
    - mysql_user: name=testdb_replic login_user=root host='192.168.1.0/255.255.255.0' password='rppass' priv='*.*:replication slave'
